services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.3.3
    command:
      - redpanda
      - start
      - --smp 1
      - --mode dev-container
    ports:
      - 9092:9092
      - 9644:9644
    volumes:
      - redpanda-data:/var/lib/redpanda/data

volumes:
  redpanda-data:
